### ISSUE TITLE
Please delete CTF flags

### ISSUE THREAD

**Issue by IntiDC** [0x42697262/birbrain-content#1]
Hello,

I think you are accidentally leaking the CTF flags for the ongoing CTF here:

https://github.com/0x42697262/birbrain-content/commits?author=0x42697262

This spoils the fun for the rest and is against the CTF rules and spirit, please take it down

**Comment by 0x42697262** [comment]
woops, removed

**Comment by IntiDC** [comment]
@0x42697262 you did not remove it, it's still in the history. Can you just make the repo private?
